In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [48]:
import sys; print(sys.executable)

/opt/homebrew/anaconda3/bin/python

In [49]:
train_base_df = pd.read_csv('../data/csv_files/train/train_base.csv')
train_static_0_0_df = pd.read_csv('../data/csv_files/train/train_static_0_0.csv')
train_static_0_1_df = pd.read_csv('../data/csv_files/train/train_static_0_1.csv')
train_static_cb_0_df = pd.read_csv('../data/csv_files/train/train_static_cb_0.csv')
train_person_1_df = pd.read_csv('../data/csv_files/train/train_person_1.csv')
train_credit_bureau_a_1_0_df = pd.read_csv('../data/csv_files/train/train_credit_bureau_a_1_0.csv')
train_credit_bureau_a_1_1_df = pd.read_csv('../data/csv_files/train/train_credit_bureau_a_1_1.csv')
train_credit_bureau_a_2_df = pd.read_csv('../data/csv_files/train/train_credit_bureau_a_2.csv')
train_applprev_1_df = pd.read_csv('../data/csv_files/train/train_applprev_1.csv')
train_tax_registry_a_1_df = pd.read_csv('../data/csv_files/train/train_tax_registry_a_1.csv')

In [50]:
# Concatenate the two credit bureau dataframes into one
train_credit_bureau_a_1_df = pd.concat([train_credit_bureau_a_1_0_df, train_credit_bureau_a_1_1_df], 
                                       axis=0, ignore_index=True)
# Concatenate the two static dataframes into one
train_static_0_df = pd.concat([train_static_0_0_df, train_static_0_1_df], 
                                       axis=0, ignore_index=True)

In [51]:
# Sort so num_group1 == 0 comes first for every case_id
train_person_1_df = train_person_1_df.sort_values(by=["case_id", "num_group1"])

# Aggregate person-level data to case-level data
person_agg = train_person_1_df.groupby("case_id").agg(
    num_applicants=("num_group1", "count"),
    max_income=("mainoccupationinc_384A", "max"),
    sum_income=("mainoccupationinc_384A", "sum"),
    primary_housing_type=("housingtype_772M", "first")
).reset_index()

# Aggregate credit bureau features per applicant
cb1_agg = train_credit_bureau_a_1_df.groupby("case_id").agg(
    # Thin-file signal (0 = Thin file, 1+ = Established)
    bureau_rowcount=("num_group1", "count"),
    
    # Overdue Amount: Both peak and average
    max_overdue_amount=("overdueamountmax_950A", "max"),
    mean_overdue_amount=("overdueamountmax_950A", "mean"),
    
    # Days Past Due: Peak severity and average discipline
    max_days_past_due=("pmts_dpdvalue_108P", "max"),
    mean_days_past_due=("pmts_dpdvalue_108P", "mean"),
    
    # Credit Amounts: Average capacity and peak exposure
    mean_past_credit_limit=("credamount_770A", "mean"),
    max_past_credit_limit=("credamount_770A", "max")
).reset_index()

# Percentage of previous contracts with any days past due
dpd_rate = (
    train_credit_bureau_a_1_df
    .assign(has_dpd=lambda x: (x["pmts_dpdvalue_108P"] > 0).astype(int))
    .groupby("case_id")["has_dpd"]
    .mean()
    .reset_index(name="dpd_contract_rate")
)

# Percentage of previous contracts with any overdue amount
overdue_rate = (
    train_credit_bureau_a_1_df
    .assign(has_overdue=lambda x: (x["overdueamountmax_950A"] > 0).astype(int))
    .groupby("case_id")["has_overdue"]
    .mean()
    .reset_index(name="overdue_contract_rate")
)

# Add the two new features to the bureau summary
cb1_agg = cb1_agg.merge(dpd_rate, on="case_id", how="left")
cb1_agg = cb1_agg.merge(overdue_rate, on="case_id", how="left")


# Aggregate monthly bureau history to the contract level first
cb2_contract_agg = train_credit_bureau_a_2_df.groupby(
    ["case_id", "num_group1"]
).agg(
    monthly_record_count=("pmts_month_158T", "count"),
    max_monthly_overdue=("pmts_overdue_1140A", "max"),
    mean_monthly_overdue=("pmts_overdue_1140A", "mean"),
    sum_monthly_overdue=("pmts_overdue_1140A", "sum")
).reset_index()

# Then aggregate the contract-level information to the applicant level
cb2_agg = cb2_contract_agg.groupby("case_id").agg(
    total_monthly_records=("monthly_record_count", "sum"),
    max_monthly_overdue=("max_monthly_overdue", "max"),
    mean_monthly_overdue=("mean_monthly_overdue", "mean"),
    sum_monthly_overdue=("sum_monthly_overdue", "sum"),
    num_bureau_contracts_with_monthly_history=("num_group1", "count")
).reset_index()

# Average number of monthly records per credit contract
cb2_agg["months_per_contract"] = (
    cb2_agg["total_monthly_records"] /
    cb2_agg["num_bureau_contracts_with_monthly_history"]
)

train_applprev_1_df["approvaldate_319D"] = pd.to_datetime(train_applprev_1_df["approvaldate_319D"]
                                                          , errors="coerce")

# Aggregate prior application features
applprev_agg = train_applprev_1_df.groupby("case_id").agg(
    
    prior_app_count=("num_group1", "count"),
    
    # Requested Amount signals (peak, average, and most recent)
    max_prior_requested_amt=("credamount_590A", "max"),
    mean_prior_requested_amt=("credamount_590A", "mean"),
    
    # Recency Signal
    most_recent_approval_date=("approvaldate_319D", "max"),
).reset_index()

# Aggregate tax registry features per applicant
tax_agg = train_tax_registry_a_1_df.groupby("case_id").agg(
    tax_filing_count=("num_group1", "count"),
    mean_tax_income=("amount_4527230A", "mean"),
    max_tax_income=("amount_4527230A", "max"),
    num_unique_employers=("name_4527232M", "nunique")
).reset_index()

In [52]:
# Create a master dataframe to hold all features
df_master = train_base_df.copy()

# Merge all aggregated features into the master dataframe
df_master = df_master.merge(train_static_0_df, on="case_id", how="left")
df_master = df_master.merge(train_static_cb_0_df, on="case_id", how="left")
df_master = df_master.merge(person_agg, on="case_id", how="left")
df_master = df_master.merge(cb1_agg, on="case_id", how="left")
df_master = df_master.merge(cb2_agg, on="case_id", how="left")
df_master = df_master.merge(applprev_agg, on="case_id", how="left")
df_master = df_master.merge(tax_agg, on="case_id", how="left")

In [53]:
# Fill NaN values for numeric columns with 0 to extract thin-file segment flag
df_master["bureau_rowcount"] = df_master["bureau_rowcount"].fillna(0)
df_master["total_monthly_records"] = df_master["total_monthly_records"].fillna(0)
df_master["prior_app_count"] = df_master["prior_app_count"].fillna(0)
df_master["tax_filing_count"] = df_master["tax_filing_count"].fillna(0)
# Thin-File Segment Flag
df_master["is_thin_file"] = (df_master["bureau_rowcount"] == 0).astype(int)

In [54]:
df_master.head(10)

,case_id,date_decision,MONTH,WEEK_NUM,target,mainoccupationinc_384A,credamount_770A,annuity_780A,days_employed_700P,education_927M,...,months_per_contract,prior_app_count,max_prior_requested_amt,mean_prior_requested_amt,most_recent_approval_date,tax_filing_count,mean_tax_income,max_tax_income,num_unique_employers,is_thin_file
0,1,2020-04-28,202004,69,0,28314.0,16373.0,600.0,1976.0,6def22f0,...,NaN,1.0,9636.0,9636.000000,2017-11-11,3.0,24916.333333,27314.0,3.0,1
1,2,2019-08-13,201908,32,0,25386.0,13707.0,725.0,NaN,10795bac,...,1.250000,4.0,29168.0,14859.750000,2016-10-13,2.0,17402.000000,20724.0,2.0,0
2,3,2019-01-01,201901,0,1,57416.0,12676.0,619.0,762.0,242b264b,...,NaN,2.0,28168.0,18844.500000,2014-06-18,0.0,NaN,NaN,NaN,1
3,4,2019-08-27,201908,34,1,31763.0,44528.0,830.0,355.0,6def22f0,...,1.000000,2.0,17924.0,12384.500000,2017-03-15,2.0,20431.000000,25348.0,2.0,0
4,5,2019-03-26,201903,12,0,11990.0,21065.0,1282.0,0.0,6def22f0,...,2.500000,0.0,NaN,NaN,NaT,2.0,28010.000000,34499.0,2.0,0
5,6,2019-12-31,201912,52,0,12166.0,9069.0,1071.0,1424.0,242b264b,...,2.571429,3.0,17161.0,10021.000000,2017-11-09,1.0,17035.000000,17035.0,1.0,0
6,7,2019-10-22,201910,42,0,NaN,16415.0,NaN,NaN,6def22f0,...,2.000000,3.0,7782.0,5773.666667,2017-01-12,2.0,25407.000000,33059.0,2.0,0
7,8,2020-04-21,202004,68,0,15939.0,18323.0,NaN,NaN,6def22f0,...,2.333333,0.0,NaN,NaN,NaT,0.0,NaN,NaN,NaN,0
8,9,2019-11-19,201911,46,1,13755.0,11738.0,1228.0,646.0,2d4a2bc4,...,2.000000,0.0,NaN,NaN,NaT,2.0,18018.500000,27136.0,2.0,0
9,10,2019-04-23,201904,16,0,17947.0,19116.0,750.0,493.0,10795bac,...,2.833333,0.0,NaN,NaN,NaT,3.0,19170.000000,23172.0,2.0,0

In [55]:
# Missing value count and percentage for every column in df_master
missing_df = pd.DataFrame({
    "missing_count": df_master.isnull().sum(),
    "pct_missing": (df_master.isnull().mean() * 100).round(2)
})

print(missing_df)

                                           missing_count  pct_missing
case_id                                                0         0.00
date_decision                                          0         0.00
MONTH                                                  0         0.00
WEEK_NUM                                               0         0.00
target                                                 0         0.00
mainoccupationinc_384A                             49651         4.97
credamount_770A                                    19959         2.00
annuity_780A                                       99677         9.97
days_employed_700P                                150571        15.06
education_927M                                         0         0.00
maritalstatus_703M                                     0         0.00
birth_259D                                             0         0.00
riskassesment_940T                                334965        33.50
numberofqueries_146L                              299821        29.98
description_5085714M                              299821        29.98
num_applicants                                         0         0.00
max_income                                         26178         2.62
sum_income                                             0         0.00
primary_housing_type                                   0         0.00
bureau_rowcount                                        0         0.00
max_overdue_amount                                337107        33.71
mean_overdue_amount                               337107        33.71
max_days_past_due                                 299821        29.98
mean_days_past_due                                299821        29.98
mean_past_credit_limit                            299821        29.98
max_past_credit_limit                             299821        29.98
dpd_contract_rate                                 299821        29.98
overdue_contract_rate                             299821        29.98
total_monthly_records                                  0         0.00
max_monthly_overdue                               359745        35.97
mean_monthly_overdue                              359745        35.97
sum_monthly_overdue                               329111        32.91
num_bureau_contracts_with_monthly_history         329111        32.91
months_per_contract                               329111        32.91
prior_app_count                                        0         0.00
max_prior_requested_amt                           200099        20.01
mean_prior_requested_amt                          200099        20.01
most_recent_approval_date                         222634        22.26
tax_filing_count                                       0         0.00
mean_tax_income                                   250148        25.01
max_tax_income                                    250148        25.01
num_unique_employers                              250148        25.01
is_thin_file                                           0         0.00

In [56]:
# percentage of thin-file applicants
df_master["is_thin_file"].mean() * 100

np.float64(29.9821)

In [57]:
missing_cols_int_float = missing_df[
    (missing_df["missing_count"] != 0)
    & (df_master.dtypes.astype(str).isin(["int64", "float64"]))
].index.tolist()
missing_cols_int_float

['mainoccupationinc_384A',
 'credamount_770A',
 'annuity_780A',
 'days_employed_700P',
 'riskassesment_940T',
 'numberofqueries_146L',
 'max_income',
 'max_overdue_amount',
 'mean_overdue_amount',
 'max_days_past_due',
 'mean_days_past_due',
 'mean_past_credit_limit',
 'max_past_credit_limit',
 'dpd_contract_rate',
 'overdue_contract_rate',
 'max_monthly_overdue',
 'mean_monthly_overdue',
 'sum_monthly_overdue',
 'num_bureau_contracts_with_monthly_history',
 'months_per_contract',
 'max_prior_requested_amt',
 'mean_prior_requested_amt',
 'mean_tax_income',
 'max_tax_income',
 'num_unique_employers']

In [58]:
# Check the missing columns that are either int or float
missing_cols_int_float = missing_df[
    (missing_df["missing_count"] != 0)
    & (df_master.dtypes.astype(str).isin(["int64", "float64"]))
].index.tolist()

In [59]:
# percentage of all rows in df_master that satisfy both conditions:
# is_thin_file == 0 --> is a rich-file applicant
# col is null
for col in missing_cols_int_float: 
    percentage = (((df_master["is_thin_file"] == 0)& df_master[col].isnull()).mean()* 100)
    print(f"{col}: {percentage:.2f}%")

mainoccupationinc_384A: 3.48%
credamount_770A: 1.41%
annuity_780A: 6.97%
days_employed_700P: 10.56%
riskassesment_940T: 3.51%
numberofqueries_146L: 0.00%
max_income: 1.84%
max_overdue_amount: 3.73%
mean_overdue_amount: 3.73%
max_days_past_due: 0.00%
mean_days_past_due: 0.00%
mean_past_credit_limit: 0.00%
max_past_credit_limit: 0.00%
dpd_contract_rate: 0.00%
overdue_contract_rate: 0.00%
max_monthly_overdue: 5.99%
mean_monthly_overdue: 5.99%
sum_monthly_overdue: 2.93%
num_bureau_contracts_with_monthly_history: 2.93%
months_per_contract: 2.93%
max_prior_requested_amt: 14.01%
mean_prior_requested_amt: 14.01%
mean_tax_income: 17.51%
max_tax_income: 17.51%
num_unique_employers: 17.51%

In [60]:
for col in missing_cols_int_float: 
    # Calculate mean between all the rows of rich-file applicants.
    mean_value = df_master.loc[df_master["is_thin_file"] == 0, col].mean()

    # Rich-file applicants: missing -> mean
    # for rich-file applicants, fill missing values with the mean of that column for rich-file applicants
    df_master.loc[df_master["is_thin_file"] == 0, col] = df_master.loc[df_master["is_thin_file"] == 0, col].fillna(mean_value)

In [61]:
for col in missing_cols_int_float: 
    percentage = (((df_master["is_thin_file"] == 0)& df_master[col].isnull()).mean()* 100)
    print(f"{col}: {percentage:.2f}%")

mainoccupationinc_384A: 0.00%
credamount_770A: 0.00%
annuity_780A: 0.00%
days_employed_700P: 0.00%
riskassesment_940T: 0.00%
numberofqueries_146L: 0.00%
max_income: 0.00%
max_overdue_amount: 0.00%
mean_overdue_amount: 0.00%
max_days_past_due: 0.00%
mean_days_past_due: 0.00%
mean_past_credit_limit: 0.00%
max_past_credit_limit: 0.00%
dpd_contract_rate: 0.00%
overdue_contract_rate: 0.00%
max_monthly_overdue: 0.00%
mean_monthly_overdue: 0.00%
sum_monthly_overdue: 0.00%
num_bureau_contracts_with_monthly_history: 0.00%
months_per_contract: 0.00%
max_prior_requested_amt: 0.00%
mean_prior_requested_amt: 0.00%
mean_tax_income: 0.00%
max_tax_income: 0.00%
num_unique_employers: 0.00%

In [62]:
# df_master.drop(columns=missing_cols_not_int_float, inplace = True)

In [63]:
df_master["date_decision"] = pd.to_datetime(df_master["date_decision"])
df_master["birth_259D"] = pd.to_datetime(df_master["birth_259D"])
# Calculate the Age in years
df_master["age"] = ((df_master["date_decision"] - df_master["birth_259D"]).dt.days / 365.25)

In [64]:
missing_df = pd.DataFrame({
    "missing_count": df_master.isnull().sum(),
    "pct_missing": (df_master.isnull().mean() * 100).round(2)
})

print(missing_df)

                                           missing_count  pct_missing
case_id                                                0         0.00
date_decision                                          0         0.00
MONTH                                                  0         0.00
WEEK_NUM                                               0         0.00
target                                                 0         0.00
mainoccupationinc_384A                             14857         1.49
credamount_770A                                     5884         0.59
annuity_780A                                       29933         2.99
days_employed_700P                                 44996         4.50
education_927M                                         0         0.00
maritalstatus_703M                                     0         0.00
birth_259D                                             0         0.00
riskassesment_940T                                299821        29.98
numberofqueries_146L                              299821        29.98
description_5085714M                              299821        29.98
num_applicants                                         0         0.00
max_income                                          7777         0.78
sum_income                                             0         0.00
primary_housing_type                                   0         0.00
bureau_rowcount                                        0         0.00
max_overdue_amount                                299821        29.98
mean_overdue_amount                               299821        29.98
max_days_past_due                                 299821        29.98
mean_days_past_due                                299821        29.98
mean_past_credit_limit                            299821        29.98
max_past_credit_limit                             299821        29.98
dpd_contract_rate                                 299821        29.98
overdue_contract_rate                             299821        29.98
total_monthly_records                                  0         0.00
max_monthly_overdue                               299821        29.98
mean_monthly_overdue                              299821        29.98
sum_monthly_overdue                               299821        29.98
num_bureau_contracts_with_monthly_history         299821        29.98
months_per_contract                               299821        29.98
prior_app_count                                        0         0.00
max_prior_requested_amt                            59967         6.00
mean_prior_requested_amt                           59967         6.00
most_recent_approval_date                         222634        22.26
tax_filing_count                                       0         0.00
mean_tax_income                                    75018         7.50
max_tax_income                                     75018         7.50
num_unique_employers                               75018         7.50
is_thin_file                                           0         0.00
age                                                    0         0.00

In [65]:
# Some checks

print(df_master.shape)
print(missing_df.shape)
print(missing_df.head())

df_master.to_parquet("../data/master.parquet")

print(df_master.isna().sum().sum())
print(df_master["target"].mean())


has_null = df_master.isna().any(axis=1)
print(pd.crosstab(df_master["is_thin_file"], has_null))

print(df_master.groupby("is_thin_file")["target"].agg(["mean", "count"]))

(1000000, 44)
(44, 2)
               missing_count  pct_missing
case_id                    0          0.0
date_decision              0          0.0
MONTH                      0          0.0
WEEK_NUM                   0          0.0
target                     0          0.0
5468205
0.191752
col_0          False   True
is_thin_file
0             544305  155874
1                  0  299821
                  mean   count
is_thin_file
0             0.164062  700179
1             0.256416  299821

In [66]:
df_master.to_parquet("../data/master.parquet")
print(df_master.shape)

(1000000, 44)

In [67]:
print(df_master.columns.tolist())

['case_id', 'date_decision', 'MONTH', 'WEEK_NUM', 'target', 'mainoccupationinc_384A', 'credamount_770A', 'annuity_780A', 'days_employed_700P', 'education_927M', 'maritalstatus_703M', 'birth_259D', 'riskassesment_940T', 'numberofqueries_146L', 'description_5085714M', 'num_applicants', 'max_income', 'sum_income', 'primary_housing_type', 'bureau_rowcount', 'max_overdue_amount', 'mean_overdue_amount', 'max_days_past_due', 'mean_days_past_due', 'mean_past_credit_limit', 'max_past_credit_limit', 'dpd_contract_rate', 'overdue_contract_rate', 'total_monthly_records', 'max_monthly_overdue', 'mean_monthly_overdue', 'sum_monthly_overdue', 'num_bureau_contracts_with_monthly_history', 'months_per_contract', 'prior_app_count', 'max_prior_requested_amt', 'mean_prior_requested_amt', 'most_recent_approval_date', 'tax_filing_count', 'mean_tax_income', 'max_tax_income', 'num_unique_employers', 'is_thin_file', 'age']

# Feature Engineering

See [Model_Feature_Catalog (1).pdf](https://drive.google.com/file/d/1dNC1biNsUu6kase-q9nfG5P9fn0vEFjo/view?usp=sharing)

In [ ]:
'''
Family 1 · Raw applicant facts 4 features
The headline facts from static_0 — income, requested credit, annuity, employment length — joined directly. These are the raw
inputs and the denominators most other families build on.
'''

# These features are already included in the df_master dataframe, so no additional code is needed here.
'''
days_employed_700P
Length of employment, in days.

Job stability proxy; longer tenure → lower risk. Direct join from static_0.
'''

'''
mainoccupationinc_384A
Stated applicant income.

Core repayment capacity and the denominator of
most ratios; higher income → lower default.

Direct join from static_0 on
case_id.
'''

'''
annuity_780A
The loan's periodic payment.

The actual cash-flow obligation; only meaningful
against income (see payment_burden).

Direct join from static_0.
'''

'''
credamount_770A
Requested credit amount.

Loan size sets both default odds (relative to
income) and loss-given-default.

Direct join from static_0.
'''

'\nFamily 1 · Raw applicant facts 4 features\nThe headline facts from static_0 — income, requested credit, annuity, employment length — joined directly. These are the raw\ninputs and the denominators most other families build on.\n'

In [ ]:
'''
Family 2 · Bureau summary 2 features
The bureau's one-line read on the applicant (its risk score, recent query count) from static_cb_0. The highest-signal family — but
present only for applicants who already have a credit history, so it is empty for thin-file applicants.
'''

# These features are already included in the df_master dataframe, so no additional code is needed here.
'''
riskassesment_940T
The bureau's own risk score (0–1).

Strongest single predictor — a pre-computed risk
opinion. Absent for thin-file applicants.

Direct join from static_cb_0; NaN
when no bureau record exists.
'''

'''
numberofqueries_146L
Count of recent credit-bureau checks.

Credit-seeking intensity; many queries signal stress
or credit hunger.

Direct join from static_cb_0.
'''

"\nFamily 2 · Bureau summary 2 features\nThe bureau's one-line read on the applicant (its risk score, recent query count) from static_cb_0. The highest-signal family — but\npresent only for applicants who already have a credit history, so it is empty for thin-file applicants.\n"

In [ ]:
'''
Family 3 · Aggregates of depth-1 tables 40 features
The bulk of the set. Each table that has many rows per loan (bureau contracts, prior applications, tax, person records) is summarised
to one row with mean / std / min / max / sum / last. This captures the shape of a history — typical level, worst case, volatility, recency
— not just a single number.
'''

'''
credit_bureau_a_1_pmts_dpdvalue_108P_mean
Mean of days-past-due across the applicant's
credit_bureau_a_1 records.

Typical days-past-due — the
applicant's baseline level.

groupby(case_id)
['pmts_dpdvalue_108P'].mean() on
credit_bureau_a_1.
'''
df_master

'\nFamily 3 · Aggregates of depth-1 tables 40 features\nThe bulk of the set. Each table that has many rows per loan (bureau contracts, prior applications, tax, person records) is summarised\nto one row with mean / std / min / max / sum / last. This captures the shape of a history — typical level, worst case, volatility, recency\n— not just a single number.\n'

In [ ]:
'''
Family 4 · Coverage & presence flags 7 features
Whether each data source exists for this applicant (thin_file, has_bureau, record counts). Absence is itself signal, and this
family defines the thin-file segment the project is about.
'''
# ***** Family 4 · Coverage & presence flags 7 features BEGIN *****
'''
has_bureau
1 if any bureau contract exists.

Presence of a credit history is itself strong signal. 1 − thin_file.
'''
df_master["has_bureau"] = (
    df_master["bureau_rowcount"] > 0
).astype(int)

'''
has_cb_summary
1 if a bureau summary row exists.

Second, independent read on the thin-file condition. base.case_id ∈ static_cb_0.case_id.
'''
df_master["has_cb_summary"] = (
    df_master["bureau_rowcount"].notna()
).astype(int)

'''
thin_file
1 if the applicant has no credit-bureau
contracts.

Defines the inclusion segment; the model is nearly
blind here, so the flag lets it treat these applicants
differently.

(credit_bureau_a_1_count == 0).
'''
df_master["thin_file"] = (
    df_master["bureau_rowcount"] == 0
).astype(int)

# Does the applicant have previous applications?
df_master["has_prev"] = (
    df_master["prior_app_count"] > 0
).astype(int)

# Does the applicant have more than one person on the application?
df_master["has_coapplicant"] = (
    df_master["num_applicants"] > 1
).astype(int)

# Does the applicant have tax records?
df_master["has_tax"] = (
    df_master["tax_filing_count"] > 0
).astype(int)

'''
person_count
Number of people on the application.

Captures joint applications (added income and
added risk).

groupby(case_id).size() on
person_1.
'''
df_master["person_count"] = df_master["num_applicants"]
# ***** Family 4 · Coverage & presence flags 7 features END *****

'\nperson_count\nNumber of people on the application.\n\nCaptures joint applications (added income and\nadded risk).\n\ngroupby(case_id).size() on\nperson_1.\n'

In [72]:
'''
Family 5 · Affordability & leverage ratios 7 features
Raw amounts made meaningful by dividing by income — payment burden, leverage, existing exposure. The “can they actually afford
it” view, and crucially it works for everyone, including thin-file applicants.
'''
# ***** Family 5 · Affordability & leverage ratios 7 features BEGIN *****
# Previous average credit exposure relative to the current requested loan
df_master["bureau_exposure_ratio"] = (
    df_master["mean_past_credit_limit"] /
    df_master["credamount_770A"]
)

# How large is the requested loan compared with stated income?
df_master["leverage"] = (
    df_master["credamount_770A"] /
    df_master["mainoccupationinc_384A"]
)

# How large is the payment compared with stated income?
df_master["payment_burden"] = (
    df_master["annuity_780A"] /
    df_master["mainoccupationinc_384A"]
)

"""
prior_credit_to_current
Prior requested credit ÷ current.

Escalation in borrowing appetite over
time.

applprev_1_credamount_590A_mean /
credamount_770A.
"""
df_master["prior_credit_to_current"] = (
    df_master["mean_prior_requested_amt"] /
    df_master["credamount_770A"]
)

# How closely does tax-record income match stated income?
df_master["income_consistency"] = (
    df_master["mean_tax_income"] /
    df_master["mainoccupationinc_384A"]
)

"""
implied_term
Credit ÷ annuity.

Rough number of payments; a long
implied term can mean a stretched
borrower.

credamount_770A / annuity_780A.
"""
df_master["implied_term"] = (
    df_master["credamount_770A"] /
    df_master["annuity_780A"]
)

"""
credit_concentration
Largest ÷ total past credit line.

Is exposure concentrated in one big
line or diversified across many.

credit_bureau_a_1_credamount_770A_max / ..._sum.
"""
df_master["credit_concentration"] = (
    df_master["max_past_credit_limit"] /
    df_master["mean_past_credit_limit"] * df_master["bureau_rowcount"]
)
# ***** Family 5 · Affordability & leverage ratios 7 features END *****

In [73]:
'''
Family 6 · Credit-behaviour ratios 6 features
How the applicant handled past credit, normalised for history length — share of contracts overdue, share ever late, severity per
contract. Behaviour, not just balances.
'''
# Average overdue amount per previous credit contract
df_master["avg_overdue_per_contract"] = (
    df_master["max_overdue_amount"] /
    df_master["bureau_rowcount"].replace(0, np.nan)
)

# Number of credit queries per previous credit contract
df_master["queries_per_contract"] = (
    df_master["numberofqueries_146L"] /
    df_master["bureau_rowcount"].replace(0, np.nan)
)

# Maximum overdue amount relative to stated income
df_master["max_overdue_to_income"] = (
    df_master["max_overdue_amount"] /
    df_master["mainoccupationinc_384A"]
)

# Average number of monthly bureau records per previous credit contract
df_master["months_per_contract"] = (
    df_master["total_monthly_records"] /
    df_master["bureau_rowcount"].replace(0, np.nan)
)

In [74]:
'''
Family 7 · Demographic / derived 3 features
Lifecycle and household context — age, income relative to tenure, how much a co-applicant adds.
'''

'\nFamily 7 · Demographic / derived 3 features\nLifecycle and household context — age, income relative to tenure, how much a co-applicant adds.\n'

In [ ]:
'''
Family 8 · Categorical encodings 19 features
The two legitimate signal categoricals (education, bureau contract class) one-hot encoded so a tree can split on a specific category.
Protected, identifier and noise categoricals were removed by the screen.
'''

'''
oh_education_927M_2d4a2bc4
One-hot indicator (1/0) for a specific category of a
signal field.

Lets a tree split on a particular category (e.g. a
risky contract class) instead of an arbitrary
ordinal order — part of the measured lift.

OneHotEncoder fit on train
(depth-1 fields taken as the
per-loan mode; rare categories
pooled).
'''
df_master["oh_education_927M_2d4a2bc4"] = (
    df_master["education_927M"] == "2d4a2bc4"
).astype(int)

'''
oh_classificationofcontr_13M_54ddc605
One-hot indicator (1/0) for a specific category of a
signal field.

Lets a tree split on a particular category (e.g. a
risky contract class) instead of an arbitrary
ordinal order — part of the measured lift.

OneHotEncoder fit on train
(depth-1 fields taken as the
per-loan mode; rare categories
pooled).
'''
df_master["oh_classificationofcontr_13M_54ddc605"] = (
    df_master["classificationofcontr_13M"] == "54ddc605"
).astype(int)

'\nFamily 8 · Categorical encodings 19 features\nThe two legitimate signal categoricals (education, bureau contract class) one-hot encoded so a tree can split on a specific category.\nProtected, identifier and noise categoricals were removed by the screen.\n'

In [76]:
'''
Family 9 · Missing-data indicators 4 features
Flags for whether key fields were present. Here missingness is structural (a field is absent because the underlying record does not
exist), so the flag itself is informative — see the dedicated page.

Status: Done
'''

'''
missing_overdue
1 if no overdue data.

Tracks absence of detailed bureau
fields (overlaps with thin-file).

credit_bureau_a_1_overdueamountmax_950A_mean.isna().
'''
df_master["missing_overdue"] = (
    df_master["max_overdue_amount"].isna()
).astype(int)

'''
missing_annuity
1 if annuity was missing.

Same structural-missingness logic. annuity_780A.isna().
'''
df_master["missing_annuity"] = (
    df_master["annuity_780A"].isna()
).astype(int)

'''
missing_days_employed
1 if employment length missing.

Often correlates with informal or
unverified employment.

days_employed_700P.isna().
'''
df_master["missing_days_employed"] = (
    df_master["days_employed_700P"].isna()
).astype(int)

'''
missing_overdue
1 if no overdue data.

Tracks absence of detailed bureau
fields (overlaps with thin-file).

credit_bureau_a_1_overdueamountmax_950A_mean.isna().
'''
# Does an important applicant field have missing information?
df_master["missing_income"] = (
    df_master["mainoccupationinc_384A"].isna()
).astype(int)

In [77]:
df_master

,case_id,date_decision,MONTH,WEEK_NUM,target,mainoccupationinc_384A,credamount_770A,annuity_780A,days_employed_700P,education_927M,...,income_consistency,implied_term,credit_concentration,avg_overdue_per_contract,queries_per_contract,max_overdue_to_income,missing_overdue,missing_annuity,missing_days_employed,missing_income
0,1,2020-04-28,202004,69,0,28314.0,16373.0,600.0,1976.000000,6def22f0,...,0.880000,27.288333,NaN,NaN,NaN,NaN,1,0,0,0
1,2,2019-08-13,201908,32,0,25386.0,13707.0,725.0,1524.501655,10795bac,...,0.685496,18.906207,5.459813,199.750000,0.250,0.031474,0,0,0,0
2,3,2019-01-01,201901,0,1,57416.0,12676.0,619.0,762.000000,242b264b,...,NaN,20.478191,NaN,NaN,NaN,NaN,1,0,0,0
3,4,2019-08-27,201908,34,1,31763.0,44528.0,830.0,355.000000,6def22f0,...,0.643233,53.648193,1.000000,500.000000,3.000,0.015742,0,0,0,0
4,5,2019-03-26,201903,12,0,11990.0,21065.0,1282.0,0.000000,6def22f0,...,2.336113,16.431357,3.282863,218.500000,2.000,0.036447,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999996,2019-06-04,201906,22,0,20809.0,14083.0,585.0,206.000000,242b264b,...,1.222284,24.073504,5.290895,153.250000,1.500,0.029458,0,0,0,0
999996,999997,2020-06-30,202006,78,1,55614.0,18717.0,1633.0,1396.000000,6def22f0,...,0.432102,11.461727,16.525089,92.750000,0.125,0.013342,0,0,0,0
999997,999998,2019-07-02,201907,26,1,37608.0,10905.0,1839.0,0.000000,6def22f0,...,0.638984,5.929853,9.078268,143.833333,0.500,0.022947,0,0,0,0
999998,999999,2020-07-28,202007,82,0,18779.0,20293.0,1642.0,1355.000000,6def22f0,...,1.141878,12.358709,1.000000,495.000000,4.000,0.026359,0,0,0,0
999999,1000000,2020-01-28,202001,56,1,14172.0,10499.0,1077.0,939.000000,242b264b,...,1.048311,9.748375,5.639142,269.000000,0.750,0.075924,0,0,0,0